### PR TITLE
Moved placeholder image into src, updated Item/index and ItemPreview …

### PR DESCRIPTION
**Pull request by randy-sykes**
…to use placeholder if nothing existed

# Description

Please include a summary of the change and which issue is fixed. Please also include relevant motivation and context. List any dependencies that are required for this change.

### CODE REVIEW

**Comment by vanessa-cooper** [comment]
Thanks @randy-sykes, I'll review the changes right away!

**Review by vanessa-cooper — CHANGES_REQUESTED** [review]
Make sure all checks pass, only then you can merge the PR.

**Comment by randy-sykes** [comment]
main_page
item_page

How the page looks if you do not include a image within new item creation.

**Review by vanessa-cooper — APPROVED** [review]
Excellent job @randy-sykes! You're now able to merge the PR.

**Pull request merged**
